#!/usr/bin/env bash
# installs certbot and configs haproxy to use ssl cert
sudo apt update
sudo apt-get install snapd
sudo apt-get remove certbot
sudo apt-get install certbot
sudo service haproxy stop
sudo certbot certonly --standalone --preferred-challenges http --http-01-port 80 -d example.com -d www.example.com
sudo ls /etc/letsencrypt/live/your_domain_name
sudo mkdir -p /etc/haproxy/certs
DOMAIN='example.com' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem > /etc/haproxy/certs/$DOMAIN.pem'
sudo chmod -R go-wrx /etc/haproxy/certs
sudo vim /etc/haproxy/haproxy.cfg

