#!/usr/bin/bash
# transfers a file from client to server
# path_to_file="$1"
# server_ip="$2"
# username="$3"
# path_to_ssh="$4"
# scp must tranfer teh file to the user home dir ~/
# strict host key checking is disabled when using scp

# check if is less than 4 arguments

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
