#!/usr/bin/env bash
# config a new nginx so that /redirect will redirect to the given url

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello, world!" | sudo tee /var/www/html/index.html
sudp sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
