#!/usr/bin/env bash
# configing HAProxy loadbalancer

# update package list
sudo apt-get -y update

# install required packages
sudo apt-get -y install software-properties-common

# add HAProxy repository and install HAProxy-2.0
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 497461-web-01 100.25.165.200:80 check
    server 497461-web-02 52.207.85.124:80 check
"

# add the HAproxy configuration to the haproxy.cfg file
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
# sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# start the HAProxy service
sudo service haproxy start
