#!/usr/bin/env bash
# configing HAProxy loadbalancer

# update package list
sudo apt-get -y update

# install required packages
sudo apt-get -y instal software-properties-common

# add HAProxy repository and install HAProxy-2.0
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balancer roundrobin
    server web1 check
    server web2 check
"

# add the HAproxy configuration to the haproxy.cfg file
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# start the HAProxy service
sudo service haproxy start
