#!/usr/bin/env bash
# displays "to infinity and beyond" indefinately
# with sleep 2
# diplays 'I am invincible' when receiving a SIGTERM signal

while true
do
    echo "to infinity and beyond"
    sleep 2

    trap 'echo "I am invincible!!!"' SIGTERM
done
